### ISSUE TITLE
temp.createWriteStream failure

### ISSUE THREAD

**Issue by simevo** [bruce/node-temp#74]
Hi. during testing we occasionally and unreproducibly get:
```
nodejs test/temp-test.js

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: temp.createWriteStream did not create a file
    at Object.<anonymous> (/<<PKGBUILDDIR>>/test/temp-test.js:58:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```
see: https://bugs.debian.org/834915

I wonder if this could be related to:
https://stackoverflow.com/a/12906805

**Comment by kapouer** [comment]
You can reproduce the failure by running
```while : ; do node test/temp-test.js; done```
from multiple (3 or 4 on my pc) terminals.

**Comment by miguelsolano** [comment]
PR has been merged and issue has been resolved.
